import = [
# uncomment the flavour you want below:
#"~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
# "~/.config/alacritty/catppuccin-macchiato.toml"
# "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Victor Mono"
style = "Bold Italic"

[font.italic]
family = "Victor Mono"
style = "Bold Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[window]
# dynamic_title = true
# option_as_alt = "Both"
dynamic_padding = true
opacity = 0.6
blur = true

[window.padding]
x = 5
y = 0
